### ISSUE TITLE
Between 0.2.0 and 0.30, sequences are no longer inherited correctly

### ISSUE THREAD

**Issue by freshtonic** [bkeepers/rosie#24]
The following code produces different output in versions `0.2.0` and `0.3.0`.

```javascript
Factory = require('rosie').Factory;

Factory.define('Base').sequence('id');
Factory.define('Derived1').extend('Base');
Factory.define('Derived2').extend('Base');

derived1 = Factory.build('Derived1');
derived2 = Factory.build('Derived2');

console.warn('derived1.id', derived1.id);
console.warn('derived2.id', derived2.id);
```

Output for `0.2.0`

```
derived1.id 1
derived2.id 2
```

Output for version `0.3.0`

```
derived1.id 1
derived2.id 1
```

The `sequence` function and the `extend` function are different between those two versions, but I'm finding it difficult to reason about the breakage.

I think the 0.2.0 behaviour is the *correct* behaviour. For example, if I had a `User` factory and an `AdminUser` factory extending it, I would expect the sequence to be shared rather than reset so that they can be inserted into the same table.

Edit:

It actually looks like `sequence` was changed to refer to `this` instead of the original `factory`, which will cause the sequence to be reset.  I'll submit a PR shortly.

**Comment by eventualbuddha** [comment]
I believe this was fixed in v0.3.1.
