### ISSUE TITLE
Should .build() invoke this.construct.create()?

### ISSUE THREAD

**Issue by andrewaustin** [bkeepers/rosie#28]
I'm trying to migrate from rosie 0.2.0 to 0.3.1.

The object I'm creating a factory for has a ```.create()``` method, but this method is async (it's a database object). Because this ```.create()``` is async, ```retval``` on line 293 will always be undefined, which results in ```Factory.build()``` always returning undefined instead of an object.

This seems like a bug. Can rosie support asynchronous ```.create()```?

**Comment by nlindley** [comment]
Just to add my two cents, I was giving rosie a try for the first time and immediately ran into unexpected behavior because of the call to `this.construct.create`. My expectation was `build` would just call the constructor function and set properties.

We use a `create` method to both initialize and save a record, which aligns with what I expected having experience with Ruby’s factory_girl where `build` and `create` have separate roles. Perhaps it would be better to remove this behavior or introduce `Factory.create` so one method doesn’t end up behaving in two different ways.

**Comment by petrbela** [comment]
From a library design perspective, trying to call `.create` on any object if it supports it just feels wrong. Seems it's coming from this commit https://github.com/chute/rosie/commit/6d5e9eceba817fc8e6a3e4c260dfdcddc8e54add which did that to support Ember. I don't think a library should be designed to fix an issue with a specific library that uses it.

I think splitting the functionality into two functions is the right way to go.

- `build` should just call the constructor, thus be synchronous
- `create` in a browser (usually) means persist on the server, which is async by nature. In Node, DB operations are also async. Therefore I think `Factory.create` should behave asynchronously (i.e. wait for the model's create to finish before invoking callback)

I agree it changes the API but thinking about it back and forth, I think it'd be the correct behavior.

**Comment by eventualbuddha** [comment]
@petrbela I'm inclined to agree with you about the `.create` method not being called by default. I put this in there in the first place to support a use case that I don't even think we have anymore (though we do still use Ember at Square, just not the same way). I wonder if removing it and releasing a v0.5.0 would be okay for folks. Actually, I wonder if we should just go v1.0.0. We're kind of abusing semver by staying in the v0.x range.

@bkeepers thoughts?

**Comment by bkeepers** [comment]
> Actually, I wonder if we should just go v1.0.0. We're kind of abusing semver by staying in the v0.x range.

:+1: 

I haven't used rosie in a while, so I don't have strong feels about the `.create`.

**Comment by taylorbarstow** [comment]
+1

I just ran into this myself, the commit 6d5e9ec made a backwards-breaking change where suddenly `.build` will now always call `.create` if it exists.  This is wonky.  It totally breaks the principle of least surprise.  Blindly looking for a method named `create`, and just calling it, is asking for trouble.

Having `build` and `create` as separate methods would make a lot of sense.  

Also, I've seen other factory implementations allow custom builder methods.  Seems like the use case targeted by 6d5e9ec could be better handled by simply passing a builder fn which does the Ember shimming that is currently baked right into rosie (and affecting lots of folks who don't use this with Ember at all).

**Comment by eventualbuddha** [comment]
Released v1.0.0 which does not call `create` on the constructor.
