### ISSUE TITLE
Create sequences based on other attributes, or options and attributes passed in through `build`

### ISSUE THREAD

**Issue by RustyToms** [bkeepers/rosie#30]
When defining an attribute, you can use an existing attribute or option to calculate a value. For example, this factory creates an object that uses a startTime (using moment.js) to create a day with a random count associated with it:

```js
Factory.define("day")
  .option("startTime", moment().subtract("days", 30))
  .attr("count", function() {
    return Math.floor(Math.random() * 100);
  })
  .attr("time", ["startTime"], function(startTime) {
    return moment(startTime).add("days", 1).valueOf();
  });

var startTime = moment().subtract("days", 10);
Factory.build("day", {}, {startTime: startTime});
// Object {count: 26, time: 1407607275019}
```

However, if I want to create a list of "days", which use the startTime as a reference point I cannot do that. Only attributes can list dependencies, and they do not receive the sequence, and sequences cannot access dependencies. It would be nice if I could do this:

```js
Factory.define("day")
  .option("startTime", moment().subtract("days", 30))
  .attr("count", function() {
    return Math.floor(Math.random() * 100);
  })
  .sequence("time", ["startTime"], function(i, startTime) {
    return moment(startTime).add("days", i - 1).valueOf();
  });

var startTime = moment().subtract("days", 10);
Factory.buildList("day", 10, {}, {startTime: startTime});
// [{count: 26, time: 1407607275019}, {count: 53, time: 1407693675019}...{count: 12, time: 1408384875019}]
```

An additional problem associated with this is that the iterator passed into sequence might not start at 1, depending on if the factory has already been used. So associated with this would be to have a way to increment starting at 0 or 1 for an attribute or a property each time buildList is called. The sort of hacky way that I got around this was by creating the "startTime" option, and mutating it. This was only possible because `startTime` is an object, rather than a string or a number.

```js
Factory.define("day")
  .option("startTime")
  .attr("count", function() {
    return Math.floor(Math.random() * 100);
  })
  .attr("time", ["startTime"], function(startTime) {
    var time = startTime.valueOf();
    startTime.add("days", 1);
    return time;
  });

var startTime = moment().subtract("days", 10);
Factory.buildList("day", 36, {}, {startTime: startTime}); // startTime is mutated
// [{count: 26, time: 1407607275019}, {count: 53, time: 1407693675019}...{count: 12, time: 1408384875019}]
```

This has the unfortunate side effect of changing the value that is passed in as the initial "startTime" which may cause trouble for someone else using this later as I would consider this unexpected behavior. Of course, trouble can be simply avoided by cloning the object passed in as the startTime, `Factory.buildList("day", 36, {}, {startTime: moment(startTime)});` but this requires the knowledge that the value will be mutated. So I think this is not really a good solution because it won't work on immutable objects, and it mutates mutable objects.

**Comment by eventualbuddha** [comment]
Closing as stale.
