### ISSUE TITLE
Lazy attributes - proposal

### ISSUE THREAD

**Issue by g00fy-** [bkeepers/rosie#7]
Hi guys, I really like the project, but I think It could use some "lazy attributes".
Let's say we want to mock the DB & we need to have consistent relations (A->B & B->A)
Therefore it would be nice to be able to create relations only after the related objects have been created. Otherwise we don't know how many related object there would be or what ids would they have. Also we would have to take care of handling relations ourselves.

I have created some wrappers (using underscore.js), that I found useful:

https://gist.github.com/4301663 

since there are dynamically computed properties in JS, I have no idea how else could one solve this problem?

**Comment by eventualbuddha** [comment]
Closing as stale.
